### ISSUE TITLE
Application feature:  Add headers

### ISSUE THREAD

**Issue by vvisperas-sensentia** [sensentia/Customer-Portal#1]
Context: When entering the Application Feature

Request:  Add Headers/underline over the Project and Environment fields, so users will know what those fields refers to

**Comment by pablobarria** [comment]
![image](https://user-images.githubusercontent.com/5231015/83191559-35a16e80-a102-11ea-8a80-739326d2d5be.png)

Added a header at the top of the menu, and a tooltip to the External link to clarify that function

**Comment by vvisperas-sensentia** [comment]
Fixed
